require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 100
  Exclude:
    - Gemfile
    - db/*
    - config/**/*

Metrics/BlockLength:
  Description: 'Checks if the length of a block exceeds some maximum value.'
  Max: 25
  Exclude:
    - spec/**/*
    - config/environments/*

Rails/LinkToBlank:
  Description: >-
    Checks that `link_to` with a `target: "_blank"` have a `rel: "noopener"` option passed to them.
    (Not relevant anymore since all modern browsers implement this functionality automatically)
  Enabled: false

Rails/OutputSafety:
  Description: 'This cop checks for the use of output safety calls like html_safe and raw.'
  Exclude:
    - config/initializers/*

RSpec/NestedGroups:
  Description: 'Checks for nested example groups.'
  Max: 5

Style/Documentation:
  Description: 'Checks for missing top-level documentation of classes and modules.'
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: 'Helps you transition from mutable string literals to frozen string literals.'
  Include:
    - app/**/*
    - spec/**/*
  Exclude:
    - spec/*
    - spec/factories/*
    - spec/support/*
